In [29]:
import numpy as np
import pandas as pd

In [30]:
data = pd.DataFrame({'f1':[1,6,1,2,8,7],'f2':[2,7,3,1,6,9]})

In [31]:
data

f1  f2
0   1   2
1   6   7
2   1   3
3   2   1
4   8   6
5   7   9

In [34]:
c1=np.array([1,2])
c2=np.array([1,3])

In [35]:
dist =pd.DataFrame(columns=['d1','d2'])

In [60]:
list1=[]
for i in range(data.shape[0]):
    sum =np.sqrt((data.f1[i] -c1[0])**2 + (data.f2[i]- c1[1])**2)
    list1.append(sum)

In [61]:
list1

[0.0,
 7.0710678118654755,
 1.0,
 1.4142135623730951,
 8.06225774829855,
 9.219544457292887]

In [62]:
list2=[]
for i in range(data.shape[0]):
    sum =np.sqrt((data.f1[i] -c2[0])**2 + (data.f2[i]- c2[1])**2)
    list2.append(sum)
list2

[1.0,
 6.4031242374328485,
 0.0,
 2.23606797749979,
 7.615773105863909,
 8.48528137423857]

In [63]:
dist.d1 =list1
dist.d2 =list2

In [64]:
dist

d1        d2
0  0.000000  1.000000
1  7.071068  6.403124
2  1.000000  0.000000
3  1.414214  2.236068
4  8.062258  7.615773
5  9.219544  8.485281

In [81]:
min_array =np.argmin(np.array(dist),axis=1)
min_array

array([0, 1, 1, 0, 1, 1], dtype=int64)

In [82]:
cluster_1 = data.loc[[0,3], :]

In [83]:
cluster_2 =data.loc[[1,2,4,5],:]

In [84]:
cluster_1

f1  f2
0   1   2
3   2   1

In [85]:
cluster_2

f1  f2
1   6   7
2   1   3
4   8   6
5   7   9

In [94]:
new_c1 = [None]*2
new_c1[0] =cluster_1.f1.mean()
new_c1[1]=cluster_1.f2.mean()

In [95]:
new_c1

[1.5, 1.5]

In [96]:
new_c2 = [None]*2
new_c2[0] =cluster_2.f1.mean()
new_c2[1]=cluster_2.f2.mean()

In [97]:
new_c2

[5.5, 6.25]

In [100]:
list1=[]
for i in range(data.shape[0]):
    sum =np.sqrt((data.f1[i] -new_c1[0])**2 + (data.f2[i]- new_c2[1])**2)
    list1.append(sum)
list1

[4.2793106921559225,
 4.562071897723665,
 3.2882366094914763,
 5.273755777432247,
 6.504805915628844,
 6.149186938124422]

In [99]:
list2=[]
for i in range(data.shape[0]):
    sum =np.sqrt((data.f1[i] -new_c2[0])**2 + (data.f2[i]- new_c2[1])**2)
    list2.append(sum)
list2

[6.189709201569974,
 0.9013878188659973,
 5.55090082779363,
 6.309714732061981,
 2.5124689052802225,
 3.132491021535417]

In [102]:
dist.d1 =list1
dist.d2 =list2
dist

d1        d2
0  4.279311  6.189709
1  4.562072  0.901388
2  3.288237  5.550901
3  5.273756  6.309715
4  6.504806  2.512469
5  6.149187  3.132491

In [121]:
min_array =np.argmin(np.array(dist),axis=1)
min_array

array([0, 1, 0, 0, 1, 1], dtype=int64)

In [122]:
cluster_1 =data.loc[[0,2,3],:]
cluster_1

f1  f2
0   1   2
2   1   3
3   2   1

In [123]:
cluster_2 =data.loc[[1,4,5],:]
cluster_2

f1  f2
1   6   7
4   8   6
5   7   9

In [124]:
new_c1[0]=cluster_1.f1.mean()
new_c1[1]=cluster_1.f2.mean()
new_c1

[1.3333333333333333, 2.0]

In [125]:
new_c2[0]=cluster_2.f1.mean()
new_c2[1]=cluster_2.f2.mean()
new_c2 

[7.0, 7.333333333333333]

In [126]:
list1=[]
for i in range(data.shape[0]):
    sum =np.sqrt((data.f1[i] -new_c1[0])**2 + (data.f2[i]- new_c2[1])**2)
    list1.append(sum)
list1

[5.343739847293799,
 4.6785562825394,
 4.346134936801765,
 6.368324391514267,
 6.79869268479038,
 5.90668171555645]

In [127]:
list2=[]
for i in range(data.shape[0]):
    sum =np.sqrt((data.f1[i] -new_c2[0])**2 + (data.f2[i]- new_c2[1])**2)
    list2.append(sum)
list2

[8.027729719194863,
 1.0540925533894596,
 7.401201103724839,
 8.069145624606803,
 1.6666666666666663,
 1.666666666666667]

In [128]:
dist.d1 =list1
dist.d2 =list2
dist

d1        d2
0  5.343740  8.027730
1  4.678556  1.054093
2  4.346135  7.401201
3  6.368324  8.069146
4  6.798693  1.666667
5  5.906682  1.666667

In [129]:
min_array =np.argmin(np.array(dist),axis=1)
min_array

array([0, 1, 0, 0, 1, 1], dtype=int64)

In [130]:
cluster_1 =data.loc[[0,2,3],:]
cluster_1

f1  f2
0   1   2
2   1   3
3   2   1

In [131]:
cluster_2 =data.loc[[1,4,5],:]
cluster_2

f1  f2
1   6   7
4   8   6
5   7   9

In [138]:
import numpy as np
data=np.array([[1,2],[6,7],[1,3],[2,1],[8,6],[7,9]])
k=2
seed=np.random.randint(1,6,2)

#c1=data[seed[0]].reshape(1,-1)
#c2=data[seed[1]].reshape(1,-1)
#clust=np.concatenate((c1,c2))

c1=np.array([1,2]).reshape(1,-1)
c2=np.array([1,3]).reshape(1,-1)
clust=np.concatenate((c1,c2))

dist=np.zeros([6,2])
n=0
while(n<10):
    for i in range(k):
        for j in range(6):
            dist[j,i]=np.sqrt(sum((clust[i,:]-data[j,:])**2))
            
    mi=np.argmin(dist,axis=1)  
    
    clust1=data[mi==0]   
    clust2=data[mi==1] 
    
    c1_upd=np.mean(clust1,axis=0) 
    c1_upd=c1_upd.reshape(1,-1)
    
    c2_upd=np.mean(clust2,axis=0) 
    c2_upd=c2_upd.reshape(1,-1)
    
    print(c1_upd)
    print(c2_upd)
    
    d1=np.sum((np.abs(c1-c1_upd)))
    d2=np.sum((np.abs(c2-c2_upd)))

    if (d1==0 and d2==0):
        break
    c1=c1_upd
    c2=c2_upd
    clust=np.concatenate((c1_upd,c2_upd))
    n=n+1
print("The cluster1:") 
print(clust1)  
print("The cluster2:") 
print(clust2)
    


TypeError: 'numpy.float64' object is not callable